name: 'Teardown Kubernetes Namespace'
description: 'After creating new namespaces via GHA, it is important to cleanup the Kubernetes cluster. This action will manage the cleanup process of a feature namespace.'

inputs:
  GCP_SA_KEY: 
    description: 'GCP Service Account Key (JSON)'
    required: true

  GKE_CLUSTER_NAME:
    description: 'Google Kubernetes Engine Cluster name'
    required: true

  GCP_ZONE: 
    description: 'GCP Zone'
    required: true

  GCP_PROJECT_ID:
    description: 'GCP Project ID'
    required: true

  GHA_ACCESS_USER: 
    description: 'GitHub Actions Access Username'
    required: false

  GHA_ACCESS_TOKEN:
    description: 'GitHub Actions Access Token'
    required: false
    
  TLD:
    description: 'Top Level Domain to create subdomain on.'
    required: false

  repos:
    description: 'Comma separated list of repositories that are deployed concurrently and require extra checks before tearing down.'
    required: false

runs:
  using: 'composite'
  steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        repository: dmsi-io/gha-env-variables
        path: gha-env-variables

    - name: Checkout
      uses: actions/checkout@v2
      with:
        repository: dmsi-io/gha-k8s-namespace
        path: gha-k8s-namespace

    - name: Export Environment Variables
      uses: dmsi-io/gha-env-variables@v1
      with:
        TLD: ${{ inputs.TLD }}
        GCP_PROJECT_ID: ${{ inputs.GCP_PROJECT_ID }}

    - name: Configure git for private modules
      if: inputs.GHA_ACCESS_USER != '' && inputs.GHA_ACCESS_TOKEN != ''
      run: git config --global url."https://${{ inputs.GHA_ACCESS_USER }}:${{ inputs.GHA_ACCESS_TOKEN }}@github.com".insteadOf "https://github.com"
      shell: bash

    ###### GCloud Setup ######

    - name: Setup GCloud Auth
      id: auth
      uses: google-github-actions/auth@v0.4.0
      with:
        credentials_json: ${{ inputs.GCP_SA_KEY }}

    - name: Set up Cloud SDK
      uses: google-github-actions/setup-gcloud@v0.2.1

    - name: Authenticate GKE cluster
      run: gcloud container clusters get-credentials ${{ inputs.GKE_CLUSTER_NAME }} --zone ${{ inputs.GCP_ZONE }} --project ${{ inputs.GCP_PROJECT_ID }}
      shell: bash

    ###### Teardown Kubernetes Artifacts ######

    - name: Remove Repo Deployment
      run: |
        if [[ $(kubectl get deployment $SERVICE_NAME -n $NAMESPACE -o=name --ignore-not-found) ]]; then 
          kubectl delete deployment $SERVICE_NAME -n $NAMESPACE
        else
          echo "could not find $SERVICE_NAME deployment in $NAMESPACE"
        fi 
      shell: bash

    - run: cat external-service-template.yaml | envsubst
      working-directory: gha-k8s-namespace/k8s
      shell: bash

    - name: Replace Service with ExternalName
      run: |
        if [[ $(kubectl get service $SERVICE_NAME -n $NAMESPACE -o=name --ignore-not-found) ]]; then 
          export EXTERNAL_SERVICE=${n##*/}
          export PORT=$(kubectl get $n -n $NAMESPACE -o json \
                  | jq -r '.spec.ports[].port')

          cat external-service-template.yaml | envsubst | kubectl apply -f - 
        else 
          echo "could not find $SERVICE_NAME service in $NAMESPACE"
        fi
      shell: bash
      working-directory: gha-k8s-namespace/k8s

    - name: Check branch exists
      id: branch-check # use this to check for `branch-exists` (`steps.branch-check.outputs.branch-exists != true`)
      # Checks if a deployment exists in namespace, if so checks if a branch of the same name exists in that repo, if so will mark branch-exists as true
      run: |
        REPOS="${{ inputs.repos }}"
        for repo in ${REPOS//,/ }
        do
          REPO_SERVICE=$(gha-env-variables/clean_variable.sh $repo)

          if [[ $(kubectl get deployment $REPO_SERVICE -n $NAMESPACE -o=name --ignore-not-found) ]]; then

            if [[ $(git ls-remote "https://github.com/${{ github.repository_owner}}/$repo.git" "${{ github.ref }}") ]]; then
              echo "::set-output name=branch-exists::true"
            else
              echo "could not find ${{ github.ref }} in ${{ github.repository_owner}}/$repo"
            fi 

          else
            echo "$REPO_SERVICE not found in $NAMESPACE"
          fi
        done
      shell: bash

    - name: Teardown Namespace'
      if: steps.branch-check.outputs.branch-exists != true
      run: |
        echo "tearing down namespace..."
      shell: bash
      